name: kafka-lib-ci

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  build:
    # OS
    runs-on: self-hosted
    # Steps: sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v3    

  dev:
    if: github.ref_name == 'master'
    uses: ./.github/workflows/deploy.yaml
    needs:
      - build
    with:
      repo: libs-snapshot
      version: ${{ github.ref_name }}
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      GITHUB_USERNAME: ${{ secrets.GH_USER }}
      GITHUB_PASSWORD: ${{ secrets.GH_TOKEN }}

  prod:
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/deploy.yaml
    needs:
      - build
    with:
      repo: libs-releases
      version: ${{ github.ref_name }}
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      GITHUB_USERNAME: ${{ secrets.GH_USER }}
      GITHUB_PASSWORD: ${{ secrets.GH_TOKEN }}
