name: kafka-lib-ci

on:
  push:
    inputs:
      version:
        type: string
        required: true

jobs:
  publish:
    # OS
    runs-on: ubuntu-22.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '20'

    - name: Publish
#      if: github.ref_type == 'tag'
      if: github.ref_name == 'cleanup'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew clean build publish -PJAR_VERSION=0.0.1
      #run: ./gradlew publish -PJAR_VERSION=${{ github.ref_name }}

