name: kafka-lib-ci

on: push

jobs:
  build:
    # OS
    runs-on: ubuntu-22.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Build
      run: ./gradlew clean build -PJAR_VERSION=${{ github.ref_name }}

    - name: Publish
      if: github.ref_type == 'tag'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew publish -PJAR_VERSION=${{ github.ref_name }}

