name: Deployment
on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
      version:
        type: string
        required: true
    secrets:      
      ARTIFACTORY_USERNAME:
        required: true
      ARTIFACTORY_PASSWORD:
        required: true
      GITHUB_USERNAME:
        required: true
      GITHUB_PASSWORD:
        required: true
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Gradle build
      run: ./gradlew clean test build artifactoryPublish -Prepo=${{ inputs.repo }} -Pgithub_user=${{ secrets.GITHUB_USERNAME }} -Partifactory_user=${{ secrets.ARTIFACTORY_USERNAME }} -Pgithub_password=${{ secrets.GITHUB_PASSWORD }} -Partifactory_password=${{ secrets.ARTIFACTORY_PASSWORD }} -PJAR_VERSION=${{ inputs.version }}
